modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "keep_equipment"
version = "${version}"
displayName = "Keep Equipment"
authors = "anticode"
description = '''
A more balanced alternative to Keep Inventory!
'''
#logoFile = ""

[[dependencies.keep_equipment]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keep_equipment]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"