# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0
maven_group=me.anticode
archives_name=keep_equipment
enabled_platforms=fabric,forge
# Minecraft properties
minecraft_version=1.20.1
# Dependencies
fabric_loader_version=0.19.3
fabric_api_version=0.92.11+1.20.1
forge_version=1.20.1-47.4.20
trinkets_version=3.10.0
curios_version=5.14.1+1.20.1
cloth_config_version=11.1.136